version: "3"
services:
  node-app:
    container_name: express-node-app-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000" 
    env_file:
      - ./.env 
    depends_on:
      - mongo  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: db
      MONGO_INITDB_ROOT_PASSWORD: example   
  mongo-express:
     image: mongo-express
     restart: always
     ports:
        - 8081:8081
     environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: db
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://db:example@mongo:27017/
     depends_on:
       - mongo  
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
      
volumes:
   mongo-db:    
  














